version: "2.3"
services:
  couchdb:
    image: apache/couchdb:2.1
    volumes:
      - ./mounts/couchdb-data:/opt/couchdb/data
    networks:
      - intranet

  redis:
    image: redis:alpine
    networks:
      - intranet

  cozy:
    build: .
    links:
      - couchdb:couchdb
      - redis:redis
    ports:
      - "8080:8080"
    volumes:
      - ./mounts/cozy-storage:/cozy/storage
      - ./mounts/cozy-conf:/cozy/.cozy
    networks:
      - web
      - intranet
    depends_on:
      - couchdb
      - redis

networks:
  web:
    external: true
  intranet:
    internal: true
