version: "2.3"
services:
  couchdb:
    image: apache/couchdb:2.1
    volumes:
      - ./mounts/couchdb-data:/opt/couchdb/data
    networks:
      - intranet

  redis:
    image: redis:alpine
    networks:
      - intranet

  cozy:
    build: .
    links:
      - couchdb:couchdb
      - redis:redis
    ports:
      - "8080:8080"
    volumes:
      - ./mounts/cozy-storage:/cozy/storage
      - ./mounts/cozy-conf:/cozy/.cozy
    networks:
      - web
      - intranet
    depends_on:
      - couchdb
      - redis
    labels:
      traefik.docker.network: "web"
      traefik.cozy_cloud.frontend.rule: Host:cozy.tams.tech,onboarding.cozy.tams.tech,settings.cozy.tams.tech,drive.cozy.tams.tech,photos.cozy.tams.tech,home.cozy.tams.tech,store.cozy.tams.tech
      traefik.cozy_cloud.port: 8080
      traefik.cozy_cloud.protocol: http
      traefik.enable: "true"

networks:
  web:
    external: true
  intranet:
    internal: true
